export const color = {
  white: '#ffffff',
  black: '#000000',
  transparent: 'transparent',
  currentColor: 'currentColor',
  primary: '#FF385C',
  onPrimary: '#ffffff',
  primaryContainer: '#FFE4E6',
  onPrimaryContainer: '#FF385C',
  error: '#b3261e',
  onError: '#ffffff',
  errorContainer: '#f9dedc',
  onErrorContainer: '#410e0b',
  background: '#ffffff',
  onBackground: '#212124',
  surface: '#f7f8fa',
  onSurface: '#212124',
  surfaceVariant: '#eaebee',
  onSurfaceVariant: '#4d5159',
  outline: '#DCDEE3',
  outlineVariant: '#868B94',

  hoverPrimary: '#E11D48',
  hoverPrimaryContainer: '#FDA4AF',
  hoverError: '#B3261E',
  hoverErrorContainer: '#e0c7c6',
  hoverBackground: '#EAEBEE',
  hoverSurface: '#DCDEE3',
  hoverSurfaceVariant: '#D1D3D8',
};
